
// Objective-C API for talking to the following Go packages
//
//
// File is generated by gomobile bind. Do not edit.
#ifndef __WaasSdkGo_FRAMEWORK_H__
#define __WaasSdkGo_FRAMEWORK_H__

#include "V1.objc.h"
#include "Universe.objc.h"

#endif
